[functions.sync-as-rankings]
verify_jwt = false

[functions.sync-football-live]
verify_jwt = false

[functions.simulate-football-live]
verify_jwt = false

[functions.sync-worldcup-results]
verify_jwt = false
